words = [
    "chrono",
    "cppcoreguidelines",
    "cxx",
    "domi",
    "kumi",
    "myapp",
    "mylib",
    "myproject",
    "niekdomi",
    "nolintbegin",
    "nolintend",
    "nolintnextline",
    "nullptr",
    "spdlog",
    "tparam",
]
